name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from file and set as environment variable
        run: |
          RELEASE_VERSION=$(cat VERSION)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Version: $RELEASE_VERSION"

      - name: Build Docker image
        run: docker build -t "blogmates/authorisation:${{ env.RELEASE_VERSION }}" .

  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push "blogmates/authorisation:${{ env.RELEASE_VERSION }}"
